create table if not exists public.satisfaction_feedback (
    id bigint generated by default as identity primary key,
    rating integer check (rating between 1 and 5),
    comment text not null default '',
    major text not null,
    semester text not null,
    keywords text not null default '',
    recommended_courses text not null default '',
    topic_1 integer not null default 0 check (topic_1 between 0 and 5),
    topic_2 integer not null default 0 check (topic_2 between 0 and 5),
    topic_3 integer not null default 0 check (topic_3 between 0 and 5),
    topic_4 integer not null default 0 check (topic_4 between 0 and 5),
    topic_5 integer not null default 0 check (topic_5 between 0 and 5),
    topic_6 integer not null default 0 check (topic_6 between 0 and 5),
    topic_7 integer not null default 0 check (topic_7 between 0 and 5),
    topic_8 integer not null default 0 check (topic_8 between 0 and 5),
    created_at timestamptz not null default now()
);

alter table public.satisfaction_feedback
    add column if not exists topic_1 integer not null default 0,
    add column if not exists topic_2 integer not null default 0,
    add column if not exists topic_3 integer not null default 0,
    add column if not exists topic_4 integer not null default 0,
    add column if not exists topic_5 integer not null default 0,
    add column if not exists topic_6 integer not null default 0,
    add column if not exists topic_7 integer not null default 0,
    add column if not exists topic_8 integer not null default 0;

alter table public.satisfaction_feedback enable row level security;

drop policy if exists "Allow anonymous feedback insert"
on public.satisfaction_feedback;

create policy "Allow anonymous feedback insert"
on public.satisfaction_feedback
for insert
to anon
with check (true);

drop policy if exists "Allow anonymous feedback summary"
on public.satisfaction_feedback;

create policy "Allow anonymous feedback summary"
on public.satisfaction_feedback
for select
to anon
using (true);