create table if not exists public.satisfaction_feedback (
    id bigint generated by default as identity primary key,
    rating integer not null check (rating between 1 and 5),
    comment text not null default '',
    major text not null,
    semester text not null,
    keywords text not null default '',
    recommended_courses text not null default '',
    created_at timestamptz not null default now()
);

alter table public.satisfaction_feedback enable row level security;

create policy "Allow anonymous feedback insert"
on public.satisfaction_feedback
for insert
to anon
with check (true);

create policy "Allow anonymous feedback summary"
on public.satisfaction_feedback
for select
to anon
using (true);